import { Job } from '@/types/job';

export const mockJobs: Job[] = [
  {
    id: "job_001",
    title: "Junior Front-End Developer",
    company: "TechFlow Solutions",
    location: "Nashville, TN",
    salary: "$65,000 - $75,000",
    postedDate: "2025-08-01",
    source: "Indeed",
    description: "We're looking for a passionate junior front-end developer to join our growing team. You'll work with React, TypeScript, and modern web technologies to build amazing user experiences.",
    requirements: ["React", "JavaScript", "CSS", "HTML", "Git"],
    isRemote: false,
    relevanceScore: 92,
    applicationStatus: "not_applied",
    tags: ["entry-level", "react", "javascript", "frontend"],
    url: "https://indeed.com/job/123"
  },
  {
    id: "job_002",
    title: "Remote Web Developer",
    company: "Digital Innovations Inc",
    location: "Remote",
    salary: "$70,000 - $85,000",
    postedDate: "2025-08-02",
    source: "RemoteOK",
    description: "Join our remote team building cutting-edge web applications using Next.js, React, and TailwindCSS. Perfect for someone with frontend experience looking to grow.",
    requirements: ["Next.js", "React", "TailwindCSS", "TypeScript", "Node.js"],
    isRemote: true,
    relevanceScore: 95,
    applicationStatus: "not_applied",
    tags: ["remote", "nextjs", "react", "tailwind", "mid-level"],
    url: "https://remoteok.io/job/456"
  },
  {
    id: "job_003",
    title: "UI/UX Developer",
    company: "Creative Studios",
    location: "Nashville, TN",
    salary: "$60,000 - $80,000",
    postedDate: "2025-07-30",
    source: "ZipRecruiter",
    description: "Seeking a creative developer who can bridge the gap between design and development. Experience with React and design tools required.",
    requirements: ["React", "CSS", "Figma", "JavaScript", "Adobe Creative Suite"],
    isRemote: false,
    relevanceScore: 78,
    applicationStatus: "applied",
    tags: ["ui-ux", "design", "frontend", "creative"],
    url: "https://ziprecruiter.com/job/789"
  },
  {
    id: "job_004",
    title: "Full Stack Developer (Junior)",
    company: "StartupTech",
    location: "Remote",
    salary: "$75,000 - $90,000",
    postedDate: "2025-08-03",
    source: "AngelList",
    description: "Join our fast-paced startup as a full-stack developer. You'll work with React, Node.js, and Python to build scalable web applications.",
    requirements: ["React", "Node.js", "Python", "MongoDB", "AWS"],
    isRemote: true,
    relevanceScore: 85,
    applicationStatus: "not_applied",
    tags: ["fullstack", "startup", "remote", "python", "aws"],
    url: "https://angel.co/job/101"
  },
  {
    id: "job_005",
    title: "Frontend Engineer",
    company: "Music City Tech",
    location: "Nashville, TN",
    salary: "$80,000 - $100,000",
    postedDate: "2025-07-29",
    source: "LinkedIn",
    description: "We're building the future of music technology. Join us as a frontend engineer working with React, TypeScript, and cutting-edge audio APIs.",
    requirements: ["React", "TypeScript", "JavaScript", "Web Audio API", "CSS"],
    isRemote: false,
    relevanceScore: 88,
    applicationStatus: "interview",
    tags: ["frontend", "music-tech", "typescript", "audio"],
    url: "https://linkedin.com/job/202"
  },
  {
    id: "job_006",
    title: "React Developer",
    company: "E-commerce Solutions",
    location: "Remote",
    salary: "$65,000 - $85,000",
    postedDate: "2025-08-04",
    source: "Indeed",
    description: "Looking for a React developer to help build our next-generation e-commerce platform. Experience with modern React patterns and state management required.",
    requirements: ["React", "Redux", "JavaScript", "REST APIs", "Git"],
    isRemote: true,
    relevanceScore: 90,
    applicationStatus: "not_applied",
    tags: ["react", "ecommerce", "remote", "redux"],
    url: "https://indeed.com/job/303"
  },
  {
    id: "job_007",
    title: "Web Developer - Healthcare",
    company: "HealthTech Solutions",
    location: "Nashville, TN",
    salary: "$70,000 - $85,000",
    postedDate: "2025-07-31",
    source: "Glassdoor",
    description: "Join our mission to improve healthcare through technology. We're looking for a web developer with React and Python experience.",
    requirements: ["React", "Python", "Django", "PostgreSQL", "HIPAA Knowledge"],
    isRemote: false,
    relevanceScore: 82,
    applicationStatus: "not_applied",
    tags: ["healthcare", "python", "react", "django"],
    url: "https://glassdoor.com/job/404"
  },
  {
    id: "job_008",
    title: "Junior Software Engineer",
    company: "Automation Specialists",
    location: "Remote",
    salary: "$68,000 - $82,000",
    postedDate: "2025-08-02",
    source: "Stack Overflow Jobs",
    description: "Perfect for someone with automation experience! We're building tools that help businesses automate their workflows using Python and React.",
    requirements: ["Python", "React", "JavaScript", "APIs", "Automation Tools"],
    isRemote: true,
    relevanceScore: 94,
    applicationStatus: "not_applied",
    tags: ["automation", "python", "react", "junior", "remote"],
    url: "https://stackoverflow.com/job/505"
  },
  {
    id: "job_009",
    title: "Frontend Developer",
    company: "FinTech Innovations",
    location: "Nashville, TN",
    salary: "$75,000 - $95,000",
    postedDate: "2025-07-28",
    source: "Built In",
    description: "Build the future of financial technology with our team. We use React, Next.js, and TypeScript to create secure and intuitive financial applications.",
    requirements: ["React", "Next.js", "TypeScript", "Financial APIs", "Security"],
    isRemote: false,
    relevanceScore: 87,
    applicationStatus: "rejected",
    tags: ["fintech", "nextjs", "typescript", "security"],
    url: "https://builtin.com/job/606"
  },
  {
    id: "job_010",
    title: "Web Application Developer",
    company: "EdTech Solutions",
    location: "Remote",
    salary: "$62,000 - $78,000",
    postedDate: "2025-08-03",
    source: "Dice",
    description: "Help us build educational tools that make learning more accessible. Looking for a developer with React and Node.js experience.",
    requirements: ["React", "Node.js", "MongoDB", "Express", "Education APIs"],
    isRemote: true,
    relevanceScore: 79,
    applicationStatus: "not_applied",
    tags: ["edtech", "react", "nodejs", "education", "remote"],
    url: "https://dice.com/job/707"
  },
  {
    id: "job_011",
    title: "Python Web Developer",
    company: "Data Analytics Corp",
    location: "Nashville, TN",
    salary: "$72,000 - $88,000",
    postedDate: "2025-07-30",
    source: "Indeed",
    description: "Combine your Python skills with web development to build data visualization dashboards and analytics tools.",
    requirements: ["Python", "Django", "React", "D3.js", "PostgreSQL"],
    isRemote: false,
    relevanceScore: 91,
    applicationStatus: "not_applied",
    tags: ["python", "data", "analytics", "django", "visualization"],
    url: "https://indeed.com/job/808"
  },
  {
    id: "job_012",
    title: "Junior Full Stack Developer",
    company: "Cloud Solutions Inc",
    location: "Remote",
    salary: "$65,000 - $80,000",
    postedDate: "2025-08-04",
    source: "FlexJobs",
    description: "Join our cloud-first company building scalable web applications. Perfect for someone with React and Python experience.",
    requirements: ["React", "Python", "AWS", "Docker", "REST APIs"],
    isRemote: true,
    relevanceScore: 86,
    applicationStatus: "applied",
    tags: ["cloud", "fullstack", "aws", "docker", "remote"],
    url: "https://flexjobs.com/job/909"
  },
  {
    id: "job_013",
    title: "React Native Developer",
    company: "Mobile First Solutions",
    location: "Nashville, TN",
    salary: "$70,000 - $90,000",
    postedDate: "2025-07-29",
    source: "AngelList",
    description: "Expand your React skills to mobile development with React Native. We're building cross-platform apps for various industries.",
    requirements: ["React Native", "React", "JavaScript", "Mobile Development", "App Store"],
    isRemote: false,
    relevanceScore: 83,
    applicationStatus: "not_applied",
    tags: ["react-native", "mobile", "cross-platform", "react"],
    url: "https://angel.co/job/010"
  },
  {
    id: "job_014",
    title: "Web Developer - AI Integration",
    company: "AI Solutions Lab",
    location: "Remote",
    salary: "$78,000 - $98,000",
    postedDate: "2025-08-01",
    source: "AI Jobs Board",
    description: "Perfect opportunity to combine web development with AI! Build interfaces for AI-powered applications using React and Python.",
    requirements: ["React", "Python", "AI/ML APIs", "TensorFlow", "OpenAI API"],
    isRemote: true,
    relevanceScore: 96,
    applicationStatus: "not_applied",
    tags: ["ai", "machine-learning", "react", "python", "remote"],
    url: "https://aijobs.com/job/111"
  },
  {
    id: "job_015",
    title: "Frontend Developer",
    company: "Gaming Studios",
    location: "Nashville, TN",
    salary: "$68,000 - $85,000",
    postedDate: "2025-07-31",
    source: "GameDev Jobs",
    description: "Build amazing gaming experiences for the web! We're looking for a frontend developer passionate about gaming and web technologies.",
    requirements: ["React", "Canvas API", "WebGL", "JavaScript", "Gaming"],
    isRemote: false,
    relevanceScore: 75,
    applicationStatus: "not_applied",
    tags: ["gaming", "webgl", "canvas", "entertainment"],
    url: "https://gamedevjobs.com/job/212"
  },
  {
    id: "job_016",
    title: "Automation Engineer (Web)",
    company: "Process Automation Inc",
    location: "Remote",
    salary: "$74,000 - $92,000",
    postedDate: "2025-08-02",
    source: "Automation Jobs",
    description: "Leverage your automation expertise to build web-based automation tools and dashboards. Python and React experience highly valued.",
    requirements: ["Python", "React", "Selenium", "APIs", "Process Automation"],
    isRemote: true,
    relevanceScore: 93,
    applicationStatus: "not_applied",
    tags: ["automation", "python", "selenium", "process", "remote"],
    url: "https://automationjobs.com/job/313"
  },
  {
    id: "job_017",
    title: "Web Developer - Startups",
    company: "Venture Builder Co",
    location: "Nashville, TN",
    salary: "$66,000 - $84,000",
    postedDate: "2025-08-03",
    source: "Startup Jobs",
    description: "Work with multiple startups to build their web presence. Variety of projects using React, Next.js, and modern web technologies.",
    requirements: ["React", "Next.js", "TailwindCSS", "Startup Experience", "Agile"],
    isRemote: false,
    relevanceScore: 89,
    applicationStatus: "not_applied",
    tags: ["startup", "variety", "nextjs", "tailwind", "agile"],
    url: "https://startupjobs.com/job/414"
  },
  {
    id: "job_018",
    title: "Remote Frontend Specialist",
    company: "Global Web Solutions",
    location: "Remote",
    salary: "$71,000 - $89,000",
    postedDate: "2025-07-30",
    source: "Remote.co",
    description: "Join our fully remote team building web applications for clients worldwide. Strong React and TypeScript skills required.",
    requirements: ["React", "TypeScript", "Next.js", "GraphQL", "Remote Work"],
    isRemote: true,
    relevanceScore: 88,
    applicationStatus: "not_applied",
    tags: ["remote", "typescript", "graphql", "global", "client-work"],
    url: "https://remote.co/job/515"
  }
];